[chore] add formatting and linting files
YouOnlyCopyOnce/YOCO pull request #2
Opened 2024-04-10 13:38 UTC by glassk

## Decsription

- husky와 lint-staged, prettier를 통한 포맷팅과 린팅 설정에 필요한 패키지를 설치하고 설정 파일을 추가하였습니다.

## ETC

-
-

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)

- [x] 필요한 테스트를 완료하였고, 기능이 제대로 실행되는지 확인 하였습니다.
- [x] 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2024-04-10 13:39 UTC, glassk commented on commitlint.config.cjs
> +};
설정 보충해주시면 감사하겠습니다 😢

2024-04-10 13:41 UTC, givvemee commented on .husky/pre-commit
> +npm run lint-staged
👍

2024-04-10 13:45 UTC, givvemee commented on commitlint.config.cjs
> +    "subject-case": [2, "never", ["sentence-case", "start-case", "pascal-case", "upper-case"]],
`never` to `always`?

2024-04-10 13:47 UTC, givvemee submitted a review, later dismissed

2024-04-10 14:09 UTC, glassk commented on commitlint.config.cjs
> +};
https://github.com/YouOnlyCopyOnce/YOCO/pull/2/commits/9b706588b2149348d4626556576dcff5d4258ebd 정규식으로 custom rule을 설정하여 개선했습니다! 

<img width="618" alt="스크린샷 2024-04-10 오후 11 04 52" src="https://github.com/YouOnlyCopyOnce/YOCO/assets/63575891/9d254868-553b-48b3-ac99-8ae254307d73">

2024-04-11 11:32 UTC, givvemee commented on commitlint.config.cjs
> +};
오 ㅋ 대박 멋집니다

2024-04-11 11:32 UTC, givvemee submitted a review, later dismissed

2024-04-11 13:00 UTC, fliklab requested changes

2024-04-11 13:00 UTC, fliklab commented on package-lock.json
> +{
yarn.lock 이 있는데 package-lock.json이 추가로 존재하는것은 적절하지 않아보입니다.

2024-04-11 13:02 UTC, glassk commented on package-lock.json
> +{
습관적으로 npm으로 설치해버렸네요 수정하겠습니다!

2024-04-11 13:04 UTC, fliklab commented on .husky/pre-commit
> +npm run lint-staged
여기서도 npm 대신 `yarn lint-staged`을 사용하는게 적절할 것같습니다.

2024-04-11 13:21 UTC, fliklab approved these changes

2024-04-11 13:21 UTC, fliklab approved these changes

2024-04-11 13:32 UTC, givvemee approved these changes

2024-04-11 13:33 UTC, merged